project:
  type: website
  output-dir: docs

website:
  title: "TESS VU - MUSA 5080 PORTFOLIO"
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - text: WEEKLY NOTES
        menu:
        - href: weekly-notes.qmd
          text: ALL NOTES
        - href: weekly-notes/week-01/week-01-notes.qmd
          text: "WEEK 1: COURSE INTRO"
        - href: weekly-notes/week-02/week-02-notes.qmd
          text: "WEEK 2: DYPLR BASICS"
        - href: weekly-notes/week-03/week-03-notes.qmd
          text: "WEEK 3: EXPLORATORY DATA ANALYSIS (EDA) & VISUALIZATION"
        - href: weekly-notes/week-03/week-03-class-lab.qmd
          text: "IN-CLASS LAB 3"
        - href: weekly-notes/week-04/week-04-notes.qmd
          text: "WEEK 4: SPATIAL DATA & GIS OPERATIONS IN R"
        - href: weekly-notes/week-04/week-04-class-lab.qmd
          text: "IN-CLASS LAB 4"
        - href: weekly-notes/week-05/week-05-notes.qmd
          text: "WEEK 5: PREDICTIVE MODELING WITH LINEAR REGRESSION"
        - href: weekly-notes/week-05/week-05-class-lab.qmd
          text: "IN-CLASS LAB 5"
        - href: weekly-notes/week-06/week-06-notes.qmd
          text: "WEEK 6: SPATIAL MACHINE LEARNING & ADVANCED REGRESSION"
        - href: weekly-notes/week-06/week-06-class-lab.qmd
          text: "IN-CLASS LAB 6"
        - href: weekly-notes/week-07/week-07-notes.qmd
          text: "WEEK 7: MODEL DIAGNOSTICS & SPATIAL AUTOCORRELATION"
        - href: weekly-notes/week-07/week-07-class-lab.qmd
          text: "IN-CLASS LAB 7"
        - href: midterm-project.qmd
          text: "WEEK 8: MIDTERM PROJECT"
        - href: weekly-notes/week-09/week-09-notes.qmd
          text: "WEEK 9: CRITICAL PERSPECTIVES ON PREDICTIVE POLICING"
        - href: weekly-notes/week-09/week-09-class-lab.qmd
          text: "IN-CLASS LAB 9"
        - href: weekly-notes/week-10/week-10-notes.qmd
          text: "WEEK 10: SPATIAL MACHINE LEARNING & ADVANCED REGRESSION"
        - href: weekly-notes/week-10/week-10-class-lab.qmd
          text: "IN-CLASS LAB 10"
      - text: LABS
        menu:
        - href: labs.qmd
          text: ALL LABS
        - href: labs/lab-1/Vu_Tessa_Assignment1.qmd
          text: "LAB 1: CENSUS DATA"
        - href: labs/lab-2/Vu_Tessa_Assignment2.qmd
          text: "LAB 2: HEALTHCARE ACCESS AND EQUITY"
        - href: midterm-project.qmd
          text: "LAB 3: MIDTERM PROJECT"
        - href: labs/lab-4/Vu_Tessa_Assignment4.qmd
          text: "LAB 4: SPATIAL PREDICTIVE ANALYSIS"
      - text: MIDTERM PROJECT
        menu: 
          - href: midterm-project.qmd
            text: MIDTERM PROJECT
          - href: midterm-project/Cao_Deng_Luu_Rigsby_Stauffer_Vu_Slides.qmd
            text: "MIDTERM SLIDES"
          - href: midterm-project/Cao_Deng_Luu_Rigsby_Stauffer_Vu_Appendix.qmd
            text: "MIDTERM APPENDIX"
      - href: final-project.qmd
        text: FINAL PROJECT
      - href: map-challenge.qmd
        text: 30-DAY MAP CHALLENGE

format:
  html:
    theme: lux
    toc: true
    code-fold: true

execute:
  freeze: auto